---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exampleco-api-sa
  namespace: default
  labels:
    app: exampleco-api
    environment: "ephemeral"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-reader
  namespace: default
  labels:
    app: exampleco-stack
    environment: "ephemeral"
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exampleco-api-job-reader
  namespace: default
  labels:
    app: exampleco-api
    environment: "ephemeral"
subjects:
  - kind: ServiceAccount
    name: exampleco-api-sa
    namespace: default
roleRef:
  kind: Role
  name: job-reader
  apiGroup: rbac.authorization.k8s.io
