apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  labels:
    app: ghcr-auth
    environment: "{{ config.environment }}"
    cluster-id: "{{ config.cluster_id }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ secrets.ghcr_dockerconfig_json }}"
